---
title: "Simple document"
output: github_document
---

```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)
library(janitor)
```

This document will show how to import data.

## Import the FAS litters CSV

```{r}
litters_df = read_csv("data/FAS_litters.csv")

litters_df = janitor::clean_names(litters_df)
# janitor:: or library(janitor)
```

## Look at the dataset

```{r}
litters_df

head(litters_df)
tail(litters_df, 10)
```

```{r eval=FALSE}
view(litters_df)
```

## Import FAS pups

Use relative paths.

```{r}
pups_df = read_csv("data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)

pups_df
```

Use absolute path.

```{r}
pups_df = read_csv("/Users/helena/data_wrangling_i/data/FAS_pups.csv")
```

## Look at read_csv options

col_names and skipping rows

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv",
           col_names = FALSE,
           skip = 1
  )
```

```{r}
litters_df = 
  read_csv(
    file = "data/FAS_litters.csv"
  )
```

What about missing data?

```{r}
litters_df = 
    read_csv(
        file = "data/FAS_litters.csv",
        na = c(".", "NA", ""))

litters_df = clean_names(litters_df)
pull(litters_df, gd0_weight)
```

What if we code `group` as a factor variable?

```{r}
litters_df = 
  read_csv(
    file = "data/FAS_litters.csv",
    na = c(".", "NA", ""),
    col_types = cols(
      Group = col_factor()
    )
  )
```









